#!/bin/bash

NAME="{{ project_name }}" # Name of the application
DJANGODIR=/var/www/{{ project_name }}/ # Django project directory
SOCKFILE=/var/www/{{ project_name }}/production/gunicorn.sock # we will communicte using this unix socket
USER={{ project_name }} # the user to run as
GROUP={{ project_name }} # the group to run as
NUM_WORKERS=3 # how many worker processes should Gunicorn spawn. 2 * CPUs + 1
DJANGO_SETTINGS_MODULE=settings # which settings file should Django use
DJANGO_WSGI_MODULE={{ project_name }}.wsgi

echo "Starting $NAME"

# Activate the virtual environment
cd $DJANGODIR
source venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE
